---
# tasks file for roles/nginx

- name: Create SSL directory
  ansible.builtin.file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0700'

- name: Generate DH Parameters with a different size (2048 bits)
  community.crypto.openssl_dhparam:
    path: /etc/nginx/ssl/dhparams.pem
    size: 2048

- name: Nginx configuration
  ansible.builtin.template:
    src: nginx/nginx-internal.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0600'
  notify: reload_nginx

- name: Recomendations
  ansible.builtin.debug:
    msg: >
      Read security recomendations for domain configuration
      https://notes.evaron.ru/operations/nginx/nginx/#security
