---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: pgalonza.linux.prepare
        tasks_from: main.yml
      vars:
        ssh_key_dir: /tmp
