---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.import_role:
        name: pgalonza.linux.prepare
        tasks_from: main.yml
      vars:
        admin_user: test_user
        ssh_key_dir: /tmp
        ansible_deploy_user: test_ansible
