namespace: pgalonza

name: linux

version: 1.0.0

readme: README.md

authors:
- Peter Galonza <p.galonza@evaron.ru>

description: This collection will help you to customize your Linux experience.

license:
- Apache-2.0

license_file: LICENSE

tags:
  - linux
  - security
  - audit
  - prompt
  - crowdsec
  - sshd
  - sysctl
  - firewalld

dependencies:
  nginxinc.nginx_core: ">=0.8.0"
  community.general: ">=8.6.2"
  community.crypto: ">=1.9.25"

repository: https://github.com/pgalonza/linux-collection

documentation: None

homepage: None

issues: None

build_ignore: []
