---
# tasks file for bash profile

- name: Add PS1
  become: false
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: "{{ bash_prompt }}"
    regexp: '^PS1=.*$'
    insertafter: '^#\sUser specific environment and startup programs$'
