---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.import_role:
        name: pgalonza.linux.bash_profile
        tasks_from: main.yml
      vars:
        bash_prompt_users:
          - test_user
