---
platforms:
  - name: Almalinux
    image: docker.io/almalinux:8
    # privileged: true
    pre_build_image: true
  - name: Ubuntu
    image: docker.io/ubuntu:23.10
    pre_build_image: false

driver:
  name: docker
dependency:
  name: galaxy
provisioner:
  name: ansible
verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
