---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect only os_family facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - os_family
    - name: Create test user
      ansible.builtin.user:
        name: test_user
        create_home: true
