---
# tasks file for auditd

- name: Install auditd RedHat
  ansible.builtin.dnf:
    name: audit
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install auditd Debian
  ansible.builtin.apt:
    name: auditd
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Configure auditd main configuration
  ansible.builtin.template:
    src: auditd/auditd.conf.j2
    dest: /etc/audit/auditd.conf
    mode: 0640
    owner: root
    group: root
  notify: restart auditd

- name: Deploy audit rules
  ansible.builtin.template:
    src: auditd/audit.rules.j2
    dest: /etc/audit/rules.d/security.rules
    mode: 0640
    owner: root
    group: root
  notify: restart auditd

- name: Start auditd
  ansible.builtin.service:
    name: auditd
    state: started
    enabled: true
  tags: molecule-notest
