---
# tasks file for crowdsec

- name: Download script.rpm.sh
  become: false
  ansible.builtin.get_url:
    url: https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh
    dest: /tmp/script.rpm.sh
    mode: '700'

- name: Execute install crowdsec repository
  ansible.builtin.command:
    cmd: /tmp/script.rpm.sh
  args:
    creates: /etc/crowdsec

- name: Install crowdsec
  ansible.builtin.dnf:
    name: "{{ crowdsec_package }}"
    state: present

- name: Install crowdsec bouncer
  ansible.builtin.dnf:
    name: "{{ crowdsec_firewall_bouncer_package }}"
    state: present

- name: Copy crowdsec configuration
  ansible.builtin.template:
    src: crowdsec/config.yaml.j2
    dest: /etc/crowdsec/config.yaml
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: restart_crowdsec

- name: Create crowdsec whitelist
  ansible.builtin.copy:
    content: "{{ crowdsec_whitelist|ansible.builtin.to_yaml(indent=2, sort_keys=false) }}"
    dest: /etc/crowdsec/parsers/s02-enrich/whitelists-external.yaml
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: restart_crowdsec
  when: crowdsec_whitelist.whitelist.ip or crowdsec_whitelist.whitelist.cidr
