---
# tasks file for crowdsec

- name: Download script
  become: false
  ansible.builtin.get_url:
    url: "https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.rpm.sh"
    dest: /tmp/script.rpm.sh
    mode: '700'

- name: Execute install crowdsec repository
  ansible.builtin.command:
    cmd: "/tmp/script.rpm.sh"

- name: Install crowdsec
  ansible.builtin.dnf:
    name: "crowdsec-{{ crowdsec_version }}-*"
    state: present

- name: Install crowdsec bouncer
  ansible.builtin.dnf:
    name: "{{ crowdsec_firewall_bouncer_redhat_package }}"
    state: present
