---
# tasks file for crowdsec

- name: Copy crowdsec configuration
  ansible.builtin.template:
    src: crowdsec/config.yaml.j2
    dest: /etc/crowdsec/config.yaml
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: restart_crowdsec

- name: Create crowdsec whitelist
  ansible.builtin.copy:
    content: "{{ crowdsec_whitelist|ansible.builtin.to_yaml(indent=2, sort_keys=false) }}"
    dest: /etc/crowdsec/parsers/s02-enrich/whitelists-external.yaml
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: restart_crowdsec
  when: crowdsec_whitelist.whitelist.ip or crowdsec_whitelist.whitelist.cidr
