---
# tasks file for crowdsec

- name: Create acquis.d
  ansible.builtin.file:
    path: /etc/crowdsec/acquis.d
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Copy crowdsec acquis
  ansible.builtin.copy:
    src: "crowdsec/acquis-{{ item }}"
    dest: "/etc/crowdsec/acquis.d/{{ item }}"
    owner: root
    group: root
    mode: 0600
  loop:
    - sshd.yaml
  notify: restart_crowdsec

- name: Copy crowdsec configuration
  ansible.builtin.template:
    src: crowdsec/config.yaml.j2
    dest: /etc/crowdsec/config.yaml
    backup: true
    owner: root
    group: root
    mode: 0600
  notify: restart_crowdsec
  when: not crowdsec_in_docker

- name: Create crowdsec whitelist
  ansible.builtin.copy:
    content: "{{ crowdsec_whitelist|ansible.builtin.to_yaml(indent=2, sort_keys=false) }}"
    dest: /etc/crowdsec/parsers/s02-enrich/01-whitelists-external.yaml
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: restart_crowdsec
  when: crowdsec_whitelist.whitelist.ip or crowdsec_whitelist.whitelist.cidr
