---
# tasks file for crowdsec

- name: Download script
  become: false
  ansible.builtin.get_url:
    url: "https://install.crowdsec.net"
    dest: /tmp/script.sh
    mode: '700'

- name: Execute install crowdsec repository
  ansible.builtin.command:
    cmd: "/tmp/script.sh"

- name: Install crowdsec
  ansible.builtin.apt:
    name: "crowdsec={{ crowdsec_version }}"
    state: present
  when: not crowdsec_in_docker

- name: Install crowdsec bouncer
  ansible.builtin.apt:
    name: "crowdsec-firewall-bouncer-{{ crowdsec_firewall_bouncer_type }}={{ crowdsec_firewall_bouncer_version }}"
    state: present