---
# tasks file for firewalld

- name: Enable Firewalld
  ansible.builtin.systemd:
    state: started
    name: firewalld
    enabled: true

- name: Add ssh custom service
  ansible.builtin.template:
    src: firewalld/ssh-custom.xml.j2
    dest: /etc/firewalld/services/ssh-custom.xml
    mode: '0644'

- name: Disable ssh
  ansible.posix.firewalld:
    zone: public
    service: ssh
    permanent: true
    state: disabled

- name: Reload Firewalld
  ansible.builtin.systemd:
    state: reloaded
    name: firewalld

- name: Enable ssh-custom
  ansible.posix.firewalld:
    zone: public
    service: ssh-custom
    permanent: true
    state: enabled
  notify:
    - restart_firewalld
