---
# tasks file for grub

- name: FSTEC kernel recomendations
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: >
      GRUB_CMDLINE_LINUX="tsx=off debugfs=no-mount vsyscall=none
      randomize_kstack_offset=1 iommu=force iommu.strict=1 iommu.passthrough=0
      init_on_alloc=1 slab_nomerge"

- name: Update grub configuration
  ansible.builtin.command: "grub-mkconfig -o /boot/grub/grub.cfg"
  when: docker_molecule == false
