---
# tasks file for linux-security

- name: Collect only os_family facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - os_family

- name: Configure SSHD
  ansible.builtin.import_tasks: sshd.yml

- name: Install crowdsec RedHat
  ansible.builtin.import_tasks: crowdsec-install-redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Install crowdsec Debian
  ansible.builtin.import_tasks: crowdsec-install-debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Install crowdsec in Docker
  ansible.builtin.import_tasks: crowdsec-install-debian.yml
  when: crowdsec_in_docker

- name: Configuration crowdsec
  ansible.builtin.import_tasks: crowdsec-configuration.yml

- name: Install auditd
  ansible.builtin.import_tasks: auditd.yml

- name: Configure sysctl
  ansible.builtin.import_tasks: sysctl.yml

- name: Configure PAM
  ansible.builtin.import_tasks: pam.yml

- name: File permissions
  ansible.builtin.import_tasks: file-permissions.yml

- name: Grub configuration
  ansible.builtin.import_tasks: grub.yml

- name: Configure firewalld
  ansible.builtin.import_tasks: firewalld.yml
  when: ansible_facts['os_family'] == "RedHat"
