---
# tasks file for linux-security

- name: Collect only os_family facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - os_family

- name: Configure SSHD
  ansible.builtin.import_tasks: sshd.yml
  tags: sshd

- name: Install crowdsec RedHat
  ansible.builtin.import_tasks: crowdsec-install-redhat.yml
  tags: crowdsec
  when: ansible_facts['os_family'] == "RedHat"

- name: Install crowdsec Debian
  ansible.builtin.import_tasks: crowdsec-install-debian.yml
  tags: crowdsec
  when: ansible_facts['os_family'] == "Debian"

- name: Install crowdsec in Docker
  ansible.builtin.import_tasks: crowdsec-docker.yml
  tags: crowdsec
  when: crowdsec_in_docker

- name: Configuration crowdsec
  ansible.builtin.import_tasks: crowdsec-configuration.yml
  tags: crowdsec

- name: Install auditd
  ansible.builtin.import_tasks: auditd.yml
  tags: auditd

- name: Configure SELinux
  ansible.builtin.import_tasks: selinux.yml
  tags: selinux
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure sysctl
  ansible.builtin.import_tasks: sysctl.yml
  tags: sysctl

- name: Configure PAM
  ansible.builtin.import_tasks: pam.yml
  tags: pam

- name: File permissions
  ansible.builtin.import_tasks: file-permissions.yml
  tags: file-permissions

- name: Grub configuration
  ansible.builtin.import_tasks: grub.yml
  tags: grub

# - name: Configure firewalld
#   ansible.builtin.import_tasks: firewalld.yml
#   when: ansible_facts['os_family'] == "RedHat"

- name: Configure nftables
  ansible.builtin.import_tasks: nftables.yml
  tags: nftables

- name: Configure journald
  ansible.builtin.import_tasks: journald.yml
  tags: journald

- name: Configure systemd system.conf
  ansible.builtin.import_tasks: systemd.yml
  tags: systemd
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Configure sudoers
  ansible.builtin.import_tasks: sudoers.yml
  tags: sudoers

- name: Configure bash security settings
  ansible.builtin.import_tasks: bash.yml
  tags: bash