---
# tasks file for linux-security

- name: Enable CRB
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled crb
  when: ansible_facts['distribution_major_version'] == '9'

- name: Enable Powertools
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled powertools
  when: ansible_facts['distribution_major_version'] == '8'

- name: Install EPEL
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - elrepo-release

- name: Configure SSHD
  import_tasks: sshd.yml

- name: Install crowdsec
  import_tasks: crowdsec.yml

- name: Install auditd
  import_tasks: auditd.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure firewalld
  import_tasks: firewalld.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure sysctl
  import_tasks: sysctl.yml

- name: Debug
  ansible.builtin.debug:
    msg: "{{ ansible_facts }}"
