---
# tasks file for linux-security

- name: Collect only os_family facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - os_family

- name: Configure SSHD
  import_tasks: sshd.yml

- name: Install crowdsec RedHat
  import_tasks: crowdsec-install-redhat.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Install crowdsec Debian
  import_tasks: crowdsec-install-debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: Configuration crowdsec
  import_tasks: crowdsec-configuration.yml

- name: Install auditd
  import_tasks: auditd.yml

- name: Configure firewalld
  import_tasks: firewalld.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Configure sysctl
  import_tasks: sysctl.yml

- name: Configure PAM
  import_tasks: pam.yml
