# tasks file for nftables

- name: Install nftables Debian
  ansible.builtin.apt:
    name: nftables
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install nftables RedHat
  ansible.builtin.dnf:
    name: nftables
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Base nftables configuration
  ansible.builtin.copy:
    src: nftables/nftables.conf
    dest: /etc/sysconfig/nftables.conf
    mode: 0600
    owner: root
    group: root
  notify: restart_nftables

- name: NFTables rules
  ansible.builtin.template:
    src: nftables/01-general-rules.nft.j2
    dest: /etc/nftables/01-general-rules.nft
    mode: 0600
    owner: root
    group: root
  notify: restart_nftables

- name: Use iptables-nft
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-nft

- name: Enable nftables
  ansible.builtin.systemd:
    name: nftables
    enabled: true
