# tasks file for nftables

- name: Install nftables Debian
  ansible.builtin.apt:
    name: nftables
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install nftables RedHat
  ansible.builtin.dnf:
    name: nftables
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Base nftables configuration
  ansible.builtin.command:
    cmd: "nft \"{{ item }}\""
  loop:
    - "flush ruleset"
    - "add table inet filter"
    - "add chain inet filter input { type filter hook input priority 0 \\; }"
    - "add rule ip filter input tcp dport {{ sshd_port }} accept"
    - "add rule inet filter input ct state established,related accept"
    - "add chain inet filter input '{ policy drop; }'"

- name: Save nftables configuration
  ansible.builtin.command:
      cmd: "nft list ruleset > /etc/nftables.conf"

- name: Enable nftables
  ansible.builtin.systemd:
    name: nftables
    enabled: true

- name: Enable nftables
  ansible.builtin.systemd:
    name: nftables
    state: started