---
# tasks file for sshd

- name: Copy ssh banner
  ansible.builtin.copy:
    src: sshd/ssh-banner
    dest: /etc/ssh/ssh-banner
    backup: yes
    owner: root
    group: root
    mode: 0600
  notify: restart_sshd

- name: Copy hardening
  ansible.builtin.copy:
    src: "sshd/{{ item }}"
    dest: "/etc/ssh/sshd_config.d/{{ item }}"
    owner: root
    group: root
    mode: 0600
  loop:
    - 00-complianceascode-hardening.conf
  notify: restart_sshd

- name: Search for files
  ansible.builtin.find:
    paths: /etc/ssh/sshd_config.d/
    contains: 'PermitRootLogin yes|GSSAPIAuthentication yes'
    file_type: file
  register: files_to_delete

- name: Delete files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ files_to_delete.files }}"
  when: files_to_delete.files | length > 0
  notify: restart_sshd

- name: Copy sshd_config
  ansible.builtin.template:
    src: sshd/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root
    group: root
    mode: 0600
    validate: /usr/sbin/sshd -t -f %s
  notify: restart_sshd
