- name: Sudo use_pty
  ansible.builtin.lineinfile:
    path: "/etc/sudoers"
    line: "Defaults use_pty"
    regexp: '^Defaults use_pty$'
    insertafter: '^#\sDefaults specification$'
    validate: "/usr/sbin/visudo --check --file=%s"

- name: Comment all lines with wheel
  block:
    - ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "# %wheel ALL=(ALL)       ALL"
        regexp: '^%wheel[\t\s]+ALL=\(ALL\)[\t\s]+ALL$'
        backrefs: true
        validate: "/usr/sbin/visudo --check --file=%s"
    - ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "# %wheel  ALL=(ALL)       NOPASSWD: ALL"
        regexp: '^%wheel[\t\s]+ALL=\(ALL\)[\t\s]+NOPASSWD:[\t\s]+ALL$'
        backrefs: true
        validate: "/usr/sbin/visudo --check --file=%s"
  when: sudoers_sudo_nopasswd

- name: Set sudo with password
  block:
    - ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "%wheel ALL=(ALL)       ALL"
        regexp: '^#\s%wheel[\t\s]+ALL=\(ALL\)[\t\s]+ALL$'
        backrefs: true
        validate: "/usr/sbin/visudo --check --file=%s"
    - ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "# %wheel  ALL=(ALL)       NOPASSWD: ALL"
        regexp: '^%wheel[\t\s]+ALL=\(ALL\)[\t\s]+NOPASSWD:[\t\s]+ALL$'
        backrefs: true
        validate: "/usr/sbin/visudo --check --file=%s"
  when: not sudoers_sudo_nopasswd
