---
# tasks file for systemctl
# https://www.redhat.com/sysadmin/ansible-linux-server-security

- name: Harden kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-kernel.conf
  loop:
    - name: kernel.core_uses_pid
      value: 1
    - name: kernel.panic
      value: 10

- name: Harden network parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-net.conf
  loop:
   - name: net.ipv4.tcp_syncookies
     value: 1
   - name: net.ipv4.tcp_synack_retries
     value: 5
   - name: net.ipv4.conf.default.log_martians
     value: 1
   - name: net.ipv4.conf.all.log_martians
     value: 1
   - name: net.ipv4.conf.all.accept_source_route
     value: 0
   - name: net.ipv4.conf.default.accept_source_route
     value: 0
   - name: net.ipv6.conf.all.accept_source_route
     value: 0
   - name: net.ipv6.conf.default.accept_source_route
     value: 0
   - name: net.ipv4.icmp_echo_ignore_broadcasts
     value: 0
   - name: net.ipv4.conf.all.rp_filter
     value: 1
   - name: net.ipv4.conf.default.rp_filter
     value: 1

- name: Disable ICMP echo and redirects
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-icmp.conf
  loop:
    - name: net.ipv4.conf.default.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.secure_redirects
      value: 0
    - name: net.ipv6.conf.all.accept_redirects
      value: 0
    - name: net.ipv6.conf.default.accept_redirects
      value: 0
    - name: net.ipv4.conf.default.send_redirects
      value: 0
    - name: net.ipv4.conf.all.send_redirects
      value: 0
    - name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
    - name: net.ipv4.icmp_echo_ignore_all
      value: "{{ sysctl_icmp_echo_ignore_all }}"

- name: Configure ip forwarding
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-forward.conf
  loop:
    - name: net.ipv4.ip_forward
      value: "{{ sysctl_forwarding_enabled }}"
    - name: net.ipv6.conf.all.forwarding
      value: "{{ sysctl_forwarding_enabled }}"

- name: Configure limits
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-limits.conf
  loop:
    - name: fs.file-max
      value: 65535
    - name: kernel.pid_max
      value: 65536
    - name: net.ipv4.ip_local_port_range
      value: 1024 65535
    - name: net.ipv4.tcp_max_syn_backlog
      value: 512
    - name: net.ipv4.tcp_fin_timeout
      value: 10
    - name: net.ipv4.tcp_max_orphans
      value: 65536
    - name: net.ipv4.tcp_keepalive_time
      value: 60
    - name: net.ipv4.tcp_keepalive_intvl
      value: 15
    - name: net.ipv4.tcp_keepalive_probes
      value: 5
    - name: net.core.netdev_max_backlog
      value: 1000
    - name: net.core.somaxconn
      value: 1024

- name: FSTEC recomendations v1
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-fstec.conf
  loop:
    - name: fs.suid_dumpable
      value: 0
    - name: fs.protected_regular
      value: 2
    - name: fs.protected_fifos
      value: 2
    - name: fs.protected_hardlinks
      value: 1
    - name: fs.protected_symlinks
      value: 1
    - name: kernel.yama.ptrace_scope
      value: 3
    - name: kernel.randomize_va_space
      value: 2
    - name: vm.mmap_min_addr
      value: 4096
    - name: dev.tty.ldisc_autoload
      value: 0
    - name: vm.unprivileged_userfaultfd
      value: 0
    - name: kernel.unprivileged_bpf_disabled
      value: "{{ sysctl_unprivileged_bpf_disabled }}"
    - name: user.max_user_namespaces
      value: "{{ sysctl_max_user_namespaces }}"
    - name: kernel.kexec_load_disabled
      value: 1
    - name: kernel.perf_event_paranoid
      value: 3
    - name: kernel.kptr_restrict
      value: 2
    - name: kernel.dmesg_restrict
      value: 1

- name: FSTEC recomendations v2
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-fstec.conf
  loop:
    - name: net.core.bpf_jit_harden
      value: 2
  tags: molecule-notest
