---
# tasks file for systemctl
# https://www.redhat.com/sysadmin/ansible-linux-server-security

- name: Harden kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-kernel.conf
  loop:
    - name: kernel.randomize_va_space
      value: 2
    - name: kernel.dmesg_restrict
      value: 1
    - name: kernel.perf_event_paranoid
      value: 2
    - name: kernel.core_uses_pid
      value: 1
    - name: kernel.panic
      value: 10
  when: docker == false

- name: Harden network parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-net.conf
  loop:
   - name: net.ipv4.tcp_syncookies
     value: 1
   - name: net.ipv4.tcp_synack_retries
     value: 5
   - name: net.ipv4.conf.default.log_martians
     value: 1
   - name: net.ipv4.conf.all.log_martians
     value: 1
   - name: net.ipv4.conf.all.accept_source_route
     value: 0
   - name: net.ipv4.conf.default.accept_source_route
     value: 0
   - name: net.ipv6.conf.all.accept_source_route
     value: 0
   - name: net.ipv6.conf.default.accept_source_route
     value: 0
   - name: net.ipv4.icmp_echo_ignore_broadcasts
     value: 0
   - name: net.ipv4.conf.all.rp_filter
     value: 1
   - name: net.ipv4.conf.default.rp_filter
     value: 1
  when: docker == false

- name: Disable ICMP echo and redirects
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-icmp.conf
  loop:
    - name: net.ipv4.conf.default.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.accept_redirects
      value: 0
    - name: net.ipv4.conf.all.secure_redirects
      value: 0
    - name: net.ipv6.conf.all.accept_redirects
      value: 0
    - name: net.ipv6.conf.default.accept_redirects
      value: 0
    - name: net.ipv4.conf.default.send_redirects
      value: 0
    - name: net.ipv4.conf.all.send_redirects
      value: 0
    - name: net.ipv4.icmp_ignore_bogus_error_responses
      value: 1
  when: docker == false

- name: Configure ip forwarding
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-forward.conf
  loop:
    - name: net.ipv4.ip_forward
      value: "{{ sysctl_forwarding }}"
    - name: net.ipv6.conf.all.forwarding
      value: "{{ sysctl_forwarding }}"
  when: docker == false

- name: Configure limits
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/90-limits.conf
  loop:
    - name: fs.file-max
      value: 65535
    - name: kernel.pid_max
      value: 65536
    - name: net.ipv4.ip_local_port_range
      value: 2000 65000
  when: docker == false
