---
# defaults file for ./roles/monitoring

yua:
  config_path: ./config.yml
  confd_path: ./conf.d
  jwt_params_path: ./jwt_params.json
  folder_id: "{{ lookup('env', 'YC_FOLDER_ID') }}"
yua_linux_metrics_detalization:
  cpu: advanced
  memory: basic
  network: basic
  storage: basic
  io: basic
  kernel: basic
yua_poll_period: 15s
yua_local_jwt_params_path: "{{ lookup('env', 'PWD') }}/jwt_params.json"
yua_labels:
  - inventory_hostname: "{{ inventory_hostname }}"
yua_docker_metrics:
  url: http://172.31.0.17:9323/metrics
  enabled: false
yua_docker_metrics_filters:
  - match: "{name=docker.engine_daemon_container_states_containers|docker.process_open_fds}"
