---
# tasks file for prepare
- name: Install user ssh key
  ansible.posix.authorized_key:
    user: "{{ owner_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key_dir }}/id_rsa.pub') }}"

- name: Add the deploy user
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    comment: Deploy user
    create_home: true
    shell: /bin/bash
    system: true

- name: Install deploy user ssh key
  ansible.posix.authorized_key:
    user: "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', '{{ ssh_key_dir }}/{{ deploy_user }}_id_rsa.pub') }}"

- name: "Deploy user permissions"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ deploy_user }}"
    content: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/visudo --check --file=%s"

# - name: Ansible user permissions in sudoers
#   community.general.sudoers:
#     name: "{{ deploy_user }}"
#     host: ALL
#     commands: ALL
#     noexec: false
#     nopassword: true
#     user: "{{ deploy_user }}"

- name: Change SSHD port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#Port"
    line: "Port {{ sshd_port }}"
    state: present
    # validate: /usr/sbin/sshd -t -f %s
  notify:
    - restart_sshd
