---
# tasks file for prepare
- name: Install user ssh key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Add the deploy user
  ansible.builtin.user:
    name: "{{ deploy_user }}"
    comment: Deploy user
    create_home: true
    shell: /bin/bash
    system: true

- name: Install deploy user ssh key
  ansible.posix.authorized_key:
    user: "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/{{ deploy_user }}_id_rsa.pub') }}"

- name: Create /etc/sudoers.d directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: "Deploy user permissions"
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ deploy_user }}"
    content: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL\n"
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/visudo --check --file=%s"

- name: Change SSHD port
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#Port"
    line: "Port {{ ssh_port }}"
    state: present
    backup: true
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - restart_sshd
