# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN \
  if [ $(command -v apt-get) ]; then \
    apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y bash python3 sudo iproute2 \
    && apt-get clean; \
  elif [ $(command -v dnf) ]; then \
    dnf makecache \
    && dnf --assumeyes install bash sudo /usr/bin/dnf-3 /usr/bin/python3 /usr/bin/python3-config iproute procps \
    && dnf clean all; \
  elif [ $(command -v yum) ]; then \
    yum makecache fast \
    && yum install -y bash sudo /usr/bin/python /usr/bin/python2-config iproute procps \
    && yum install -y http://mirror.centos.org/centos/7/os/x86_64/Packages/yum-plugin-copr-1.1.31-54.el7_8.noarch.rpm http://mirror.centos.org/centos/7/os/x86_64/Packages/libseccomp-2.3.1-4.el7.x86_64.rpm \
    && yum copr enable -y jsynacek/systemd-backports-for-centos-7 \
    && yum update --disableplugin=priorities -y systemd \
    && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf \
    && yum clean all; \
  elif [ $(command -v zypper) ]; then \
    zypper refresh \
    && zypper install -y bash python3 sudo iproute2 \
    && zypper clean -a; \
  elif [ $(command -v apk) ]; then \
    apk update \
    && apk add --no-cache bash python3 sudo; \
    echo 'rc_provide="loopback net"' >> /etc/rc.conf; \
  elif [ $(command -v xbps-install) ]; then \
    xbps-install -Syu \
    && xbps-install -y bash python3 sudo iproute2 \
    && xbps-remove -O; \
  fi