---
# defaults file for security

# Molecule
docker_molecule: false

# SSHD
sshd_log_level: VERBOSE
sshd_port: 22
sshd_address_famaly: any
sshd_login_grace_time: 1m
sshd_max_auth_tries: 3
sshd_max_sessions: 10
sshd_allow_agent_forwarding: 'yes'
sshd_allow_tcp_forwarding: 'yes'
sshd_x11_forwarding: 'no'
sshd_print_motd: 'no'
sshd_tcp_keep_alive: 'yes'
sshd_client_alive_interval: 300
sshd_client_alive_count_max: 3
sshd_use_dns: 'no'
sshd_allow_users:
  - "{{ ansible_user }}"
sshd_sftp_server_path: /usr/libexec/openssh/sftp-server
sshd_listen_address_ipv4: '0.0.0.0'
sshd_listen_address_ipv6: '::'
sshd_deny_users:
  - root
  - admin
  - sa

# Crowdsec
crowdsec_use_wal: 'true'
crowdsec_whitelist:
  name: external/whitelists
  description: "Whitelist events from global addresses"
  whitelist:
    reason: "global ipv4/ipv6 ip/ranges"
    ip: []
    cidr: []
crowdsec_in_docker: true
crowdsec_version: 1.6.4
crowdsec_firewall_bouncer_type: nftables
crowdsec_firewall_bouncer_version: 0.0.31

# Sysctl
unprivileged_bpf_enabled: false
forwarding_enabled: true
user_namespace_enabled: true
icmp_echo_ignore_all: true

# PAM
wheel_users: []