---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: pgalonza.linux.security
        tasks_from: main.yml
      vars:
        ansible_user: root
        docker: true
