---
platforms:
  - name: Almalinux
    image: docker.io/almalinux:8
    platform: x86_64
    privileged: true
    pre_build_image: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /usr/sbin/init
    dockerfile: ../common/Dockerfile.j2
  - name: Debian
    image: docker.io/debian:12.1
    platform: x86_64
    privileged: true
    pre_build_image: false
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    dockerfile: ../common/Dockerfile.j2

driver:
  name: docker
dependency:
  name: galaxy
provisioner:
  name: ansible
verifier:
  name: testinfra

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
