---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect only os_family facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - os_family
    - name: Install RedHat packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - firewalld
        - openssh-server
        - dnf-plugins-core
        - procps-ng
      when: ansible_facts['os_family'] == "RedHat"
    - name: Install Debian packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - openssh-server
        - apt-utils
        - dialog
        - whiptail
      when: ansible_facts['os_family'] == "Debian"
    - name: Create default gradle file
      ansible.builtin.copy:
        content: 'GRUB_CMDLINE_LINUX=""'
        dest: /etc/default/grub
        mode: '0600'
    - name: Create acquis for crowdsec
      ansible.builtin.copy:
        content: |
          filenames:
          - /var/log/auth.log
          - /var/log/syslog
          labels:
            type: syslog
        dest: /etc/crowdsec/acquis.yaml
        mode: '0600'
