---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Collect only os_family facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - os_family
    - name: Install RedHat packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - firewalld
        - openssh-server
        - dnf-plugins-core
        - procps-ng
      when: ansible_facts['os_family'] == "RedHat"
    - name: Install Debian packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - openssh-server
        - apt-utils
        - dialog
        - whiptail
      when: ansible_facts['os_family'] == "Debian"
    - name: Ensure /etc/sysctl.d directory exists
      ansible.builtin.file:
        path: /etc/sysctl.d
        state: directory
        mode: '0755'
    - name: Ensure /etc/nftables directory exists
      ansible.builtin.file:
        path: /etc/nftables
        state: directory
        mode: 0755
        owner: root
        group: root
    - name: Create default gradle file
      ansible.builtin.copy:
        content: 'GRUB_CMDLINE_LINUX=""'
        dest: /etc/default/grub
        mode: '0600'
    - name: Create crowdsec directory
      ansible.builtin.file:
        state: directory
        path: /etc/crowdsec
        mode: '0700'
    - name: Create acquis for crowdsec
      ansible.builtin.copy:
        content: |
          filenames:
            - /var/log/auth.log
            - /var/log/syslog
          labels:
            type: syslog
        dest: /etc/crowdsec/acquis.yaml
        mode: '0600'
    - name: Ensure SSH host keys exist (AlmaLinux)
      block:
        - name: Generate SSH host keys
          ansible.builtin.command: ssh-keygen -t {{ item }} -f /etc/ssh/ssh_host_{{ item }}_key -N ''
          with_items:
            - rsa
            - ecdsa
            - ed25519
        - name: Set correct permissions
          ansible.builtin.file:
            path: "{{ item }}"
            mode: "0600"
          with_fileglob:
            - /etc/ssh/ssh_host_*
      when: ansible_os_family == "RedHat"
    - name: Create SSH privilege separation directory (Ubuntu)
      ansible.builtin.file:
        path: /run/sshd
        state: directory
        mode: '0755'
        owner: root
        group: root
      when: ansible_os_family == "Debian"
