---
# tasks file for lynis

- name: Unarchive lynis
  ansible.builtin.unarchive:
    src: "https://github.com/CISOfy/lynis/archive/refs/tags/{{ lynis_version }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/lynis-{{ lynis_version }}"

- name: Execute lynis
  ansible.builtin.command:
    cmd: ./lynis audit system --no-colors --auditor "{{ auditor_name }}"
  args:
    chdir: "/tmp/lynis-{{ lynis_version }}"
  register: lynis_report

- name: Create report from output
  become: false
  ansible.builtin.copy:
    dest: "{{ audit_dir }}/lynis-report.txt"
    content: >
      {{ lynis_report.stdout|regex_replace("\u001b\[[0-9]{1,3}C", '', multiline=True) }}
    mode: '0600'
  delegate_to: localhost

- name: Copy lynis dat report
  become: false
  ansible.builtin.fetch:
    src: /var/log/lynis-report.dat
    dest: "{{ audit_dir }}/lynis-report.dat"
    mode: '0600'
