---
# tasks file for audit

- name: Create audit dir
  become: false
  ansible.builtin.file:
    path: "{{ audit_dir }}"
    state: directory
    mode: '0700'
  delegate_to: localhost

- name: Execute audit
  ansible.builtin.import_tasks: audit.yml
  tags: audit

- name: Execute lynis
  ansible.builtin.import_tasks: lynis.yml
  tags: lynis

- name: Execute OpenSCAP
  ansible.builtin.import_tasks: openscap.yml
  tags:
    - openscap
    - molecule-notest

- name: Execute kvrt
  ansible.builtin.import_tasks: kvrt.yml
  tags:
    - kvrt
    - molecule-notest
