---
# tasks file for audit

- name: Create audit dir
  become: false
  ansible.builtin.file:
    path: "{{ audit_dir }}"
    state: directory
    mode: '0700'
  delegate_to: localhost

- name: Execute audit
  ansible.builtin.import_tasks: audit.yml

- name: Execute lynis
  ansible.builtin.import_tasks: lynis.yml

- name: Execute kvrt
  ansible.builtin.import_tasks: kvrt.yml
