---
# handlers file for security

- name: Reload ssh server
  ansible.builtin.systemd:
    state: reloaded
    name: sshd
  listen: restart_sshd
  when: ansible_facts['os_family'] == "RedHat"

- name: Reload ssh server
  ansible.builtin.systemd:
    state: reloaded
    name: ssh
  listen: restart_sshd
  when: ansible_facts['os_family'] == "Debian"

- name: Reload crowdsec
  ansible.builtin.systemd:
    state: restarted
    name: crowdsec
  listen: restart_crowdsec

- name: Reload Firewalld
  ansible.builtin.systemd:
    state: reloaded
    name: firewalld
  listen: restart_firewalld
  when: ansible_facts['os_family'] == "RedHat"

- name: Reload nftables
  ansible.builtin.systemd:
    state: reloaded
    name: nftables
  listen: restart_nftables

- name: Update grub configuration
  ansible.builtin.command:
    cmd: "grub-mkconfig -o /boot/grub/grub.cfg"
    removes: /boot/grub/grub.cfg
  listen: regenerate_grub

- name: Update grub configuration
  ansible.builtin.command:
    cmd: "grub-mkconfig -o /boot/grub/grub.cfg"
    removes: /boot/grub2/grub.cfg
  listen: regenerate_grub
