---
# handlers file for security

- name: Reload ssh server
  ansible.builtin.systemd:
    state: reloaded
    name: sshd
  listen: restart_sshd

- name: Reload crowdsec
  ansible.builtin.systemd:
    state: reloaded
    name: crowdsec
  listen: restart_crowdsec

- name: Reload Firewalld
  ansible.builtin.systemd:
    state: reloaded
    name: firewalld
  listen: restart_firewalld
  when: ansible_facts['os_family'] == "RedHat"
