---
name: Molecule CI/CD
on:
  push:
    branches:
      - main

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - audit
          - bash_profile
          - nginx
          - security
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Molecule dependencies
        run: pip3 install -r ./extensions/molecule/requirements.txt
      - name: Install collection
        run: ansible-galaxy collection install ./
      - name: Run Molecule tests
        run: |
          cd ./extensions
          molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
