name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  molecule-workflow:
    uses: ./.github/workflows/molecule.yaml
  create-release:
    runs-on: ubuntu-latest
    needs: molecule-workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: ./configs/cliff.toml
          args: --verbose
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./"
          prerelease: false
          name: "linux ${{ github.ref_name }}"
          bodyFile: "git-cliff/CHANGELOG.md"
