---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Testing role
      ansible.builtin.include_role:
        name: pgalonza.linux.audit
        tasks_from: main.yml
      vars:
        auditor_name: Molecule
        ansible_user: root
